language: ruby
rvm:
 - 2.6.0
 - jruby

bundler_args: --without production

services:
  - postgresql

addons:
  postgresql: "11.2"

before_script:
  - psql -c 'create database pgapp_test;' -U postgres
