addons: 
before_script:
- psql -c 'create database pgapp_test;' -U postgres
bundler_args: "--without production"
language: ruby
postgresql: '11.2'
rvm:
- 2.6.0
services:
- postgresql
deploy:
  api_key:
    secure: GBK5hu/P3Nv6CkY6DSGXjfXH0mPrAFxKfitogdWlSB0rUPd3jM3CjWqf35TU5m1geFNajhumj/YJSuTLSxTFCLixN1Gkst17hMBojI9AGKN+6zCIdn4TpgPHAII9oCN8RptS5l0rn+F17pM1muYVFIE2Em3EqA1fgDZ/1l+WWx60vnNpJx5OGhDseQpDoKP798ED+Uw5Sf126sdp0UoU+DH6qDKGvkl+EbuHqhyEx92bPl/aqMhtFuH0PsZUHTjjFYVESxD1ZHblbBtDrTiLgbBvPyk4t2g9W3vNCgtUF54CZDY0Jh3U9539ADNfTCVbXXRLgJjAYDLDQZ54GEA5tKxMAC3DYONu/SZIGf/PR1SHUwsPxU0R8ve2Y+m1gAMGTpT6E18QOLZS4GpbnfRxc6k0yHCOHn0ZFLOF73bhyBuypNBGzGuQyT6+Xt1DBwDEnFNMWopUP2CaETlG3lt6YgsKwaxO4JNUv4GVkJhxrWit7Rxk+682Go76uiNF1eQ5/OlI2YwHDQlohS+ZAl5JEf94rIwVxUC2LQ++FYZABEgjJcwODt8h6sSfKE42NXSF5+eRkZ+Gzb3woGhNvbwKJAoa3b+iuNF0i3yuyvEi11txIpeB83dsj4CJYPx/8WgTl+k6WODlRCpxD3a0oyH+WPAoubdHNRWys0vmWzbkvaI=
