addons: 
before_script:
- psql -c 'create database pgapp_test;' -U postgres
bundler_args: "--without production"
language: ruby
postgresql: '11.2'
rvm:
- 2.6.0
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: quqr+EjXIa3hY+8yKuXfEcuyBomBv76GM/baZaD2QMq/oyRlqHpWcRy7gdJM3cyU4cF866dLO3ZJy8P4qSZ4aKkMAQkq26I2JFMuAKRcras4rSx2rkM/c+B1flLTPLGMcjrKz4FqWyWD+1qJe1VxShAx/KGi5D1UNYDZ6Vl16vO1nHO6XDateYmo0XlvpdNMS8DyTsphJMLh2wNjQOz4A7si87f37PZcaf7tthyvMYOAIlaSgHe0HG39wqKFWHAAOkiXAYXWA+AhFaOSUV+TYy7XMDG5lpBZA0JU/CNC0Y/uj7b5oari1x39OqjJCgrpukAU+MqEQH3y3ocM+HFTzFmCGEW6Dp1EIu7BJM8cpCjt4mEsIve9m7qhMXgJhuk/KyBjyXjAwBX8mpdEx3XeEPQC2DDyEJSZCzVjLOYecSNmUWvjniUmjRvrnqb6jtl1T4NXeLN2FigqwpchLnPvF1UzEas3jrZiG/CrbJmzbFbWq4/f5gO1Ly9oH+95CDmw3t/GvBFaj7mCZuSwhgu9mEtIqPf8plGHWjl5rg2fpFnlBmGQPH07btBmtixTLJlImY2XEEzgtaaxwhbSSMKdtSCmhJ8Tc6vcqz48NW9NWvD7qJ/KefKV9/E2DWt4gjj3E6TlwdGxMcp+mbSUPct/pmthQ8Mc+EmhBxmx//YpR7s=
